/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * leg_spd.c
 *
 * Code generation for function 'leg_spd'
 *
 */

/* Include files */
#include "leg_spd.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Definitions */
void leg_spd(float dphi1, float dphi4, float phi1, float phi4, float spd[2])
{
  float t10_tmp;
  float t12_tmp;
  float t2;
  float t21;
  float t22;
  float t23;
  float t24;
  float t29;
  float t3;
  float t30;
  float t33;
  float t34;
  float t35;
  float t36;
  float t37;
  float t38;
  float t4;
  float t5;
  float t51;
  float t59;
  float t60;
  float t64;
  float t66;
  float t73;
  /* LEG_SPD */
  /*     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     09-May-2026 17:30:22 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t10_tmp = t2 * 0.11F;
  t12_tmp = t4 * 0.11F;
  t21 = t2 * 0.02904F;
  t22 = t3 * 0.02904F;
  t23 = t4 * 0.02904F;
  t24 = t5 * 0.02904F;
  t29 = t10_tmp - t3 * 0.11F;
  t30 = t12_tmp - t5 * 0.11F;
  t33 = t21 - t22;
  t34 = t23 - t24;
  t35 = t4 * t29 * 0.22F;
  t36 = t5 * t29 * 0.22F;
  t37 = t2 * t30 * 0.22F;
  t38 = t3 * t30 * 0.22F;
  t51 = t29 * t29 + t30 * t30;
  t59 = 1.0F / ((t22 - t21) + t51);
  t60 = t59 * t59;
  t64 = sqrtf((t33 * t33 + t34 * t34) - t51 * t51);
  t29 = 1.0F / t64;
  t66 = (t24 - t23) + t64;
  t73 = atanf(t59 * t66) * 2.0F;
  t30 = cosf(t73);
  t64 = sinf(t73);
  t73 = 1.0F / (t60 * (t66 * t66) + 1.0F);
  t23 = ((t23 + t37) - t35) * t60 * t66 +
        t59 * (t21 - t29 *
                         ((t2 * t34 * 0.05808F - t4 * t33 * 0.05808F) +
                          t51 * (t35 - t37) * 2.0F) /
                         2.0F);
  t29 = ((t24 + t38) - t36) * t60 * t66 +
        t59 * (t22 - t29 *
                         ((t3 * t34 * 0.05808F - t5 * t33 * 0.05808F) +
                          t51 * (t36 - t38) * 2.0F) /
                         2.0F);
  t2 = t10_tmp + t30 * 0.132F;
  t4 = t12_tmp + t64 * 0.132F;
  t66 = t30 * t73;
  t21 = t66 * t29;
  t64 *= t73;
  t51 = t64 * t29;
  t59 = t2 * t2;
  t60 = 1.0F / t2;
  t30 = t4 * t4 + t59;
  t29 = 1.0F / sqrtf(t30);
  t73 = 1.0F / t30;
  t66 = t10_tmp - t66 * t23 * 0.264F;
  t30 = t12_tmp - t64 * t23 * 0.264F;
  spd[0] = dphi4 * t29 * (t4 * t21 * 0.528F - t2 * t51 * 0.528F) / 2.0F +
           dphi1 * t29 * (t4 * t66 * 2.0F - t2 * t30 * 2.0F) / 2.0F;
  t29 = t4 * (1.0F / t59);
  spd[1] =
      dphi1 * t59 * t73 * (t60 * t66 + t29 * t30) -
      dphi4 * t59 * t73 * (t60 * (0.0F - t21 * 0.264F) - t29 * (t51 * 0.264F));
}

/* End of code generation (leg_spd.c) */
