/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * leg_pos.c
 *
 * Code generation for function 'leg_pos'
 *
 */

/* Include files */
#include "leg_pos.h"
#include "atan2.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Definitions */
void leg_pos(float phi1, float phi4, float pos[2])
{
  float t12;
  float t13;
  float t14;
  float t15;
  float t2;
  float t3;
  float t4;
  float t5;
  float t6;
  float t8;
  /* LEG_POS */
  /*     POS = LEG_POS(PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     09-May-2026 17:30:21 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t6 = t2 * 0.11F;
  t8 = t4 * 0.11F;
  t12 = t2 * 0.02904F;
  t13 = t3 * 0.02904F;
  t14 = t4 * 0.02904F;
  t15 = t5 * 0.02904F;
  t4 = t6 - t3 * 0.11F;
  t2 = t8 - t5 * 0.11F;
  t3 = t12 - t13;
  t5 = t14 - t15;
  t2 = t4 * t4 + t2 * t2;
  t2 = atanf(1.0F / ((t13 - t12) + t2) *
             ((t15 - t14) + sqrtf((t3 * t3 + t5 * t5) - t2 * t2))) *
       2.0F;
  t4 = t8 + sinf(t2) * 0.132F;
  t2 = t6 + cosf(t2) * 0.132F;
  pos[0] = sqrtf(t4 * t4 + t2 * t2);
  pos[1] = b_atan2(t4, t2);
}

/* End of code generation (leg_pos.c) */
