/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * leg_conv.c
 *
 * Code generation for function 'leg_conv'
 *
 */

/* Include files */
#include "leg_conv.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Definitions */
void leg_conv(float F, float Tp, float phi1, float phi4, float T[2])
{
  float t112;
  float t114_tmp;
  float t118_tmp;
  float t130;
  float t133_tmp;
  float t141_tmp;
  float t16_tmp;
  float t185;
  float t18_tmp;
  float t33_tmp;
  float t34_tmp;
  float t35_tmp;
  float t36_tmp;
  float t49_tmp;
  float t4_tmp;
  float t50_tmp;
  float t57_tmp;
  float t58_tmp;
  float t5_tmp;
  float t60_tmp;
  float t61_tmp;
  float t62_tmp;
  float t6_tmp;
  float t7_tmp;
  float t91_tmp;
  /* LEG_CONV */
  /*     T = LEG_CONV(F,Tp,PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     09-May-2026 17:30:22 */
  t4_tmp = cosf(phi1);
  t5_tmp = cosf(phi4);
  t6_tmp = sinf(phi1);
  t7_tmp = sinf(phi4);
  t16_tmp = t4_tmp * 0.11F;
  t18_tmp = t6_tmp * 0.11F;
  t33_tmp = t4_tmp * 0.02904F;
  t34_tmp = t5_tmp * 0.02904F;
  t35_tmp = t6_tmp * 0.02904F;
  t36_tmp = t7_tmp * 0.02904F;
  t49_tmp = t16_tmp - t5_tmp * 0.11F;
  t50_tmp = t18_tmp - t7_tmp * 0.11F;
  t57_tmp = t33_tmp - t34_tmp;
  t58_tmp = t35_tmp - t36_tmp;
  t185 = t6_tmp * t49_tmp * 0.22F;
  t60_tmp = t7_tmp * t49_tmp * 0.22F;
  t61_tmp = t4_tmp * t50_tmp * 0.22F;
  t62_tmp = t5_tmp * t50_tmp * 0.22F;
  t91_tmp = t49_tmp * t49_tmp + t50_tmp * t50_tmp;
  t49_tmp = 1.0F / ((t34_tmp - t33_tmp) + t91_tmp);
  t50_tmp = t49_tmp * t49_tmp;
  t112 = sqrtf((t57_tmp * t57_tmp + t58_tmp * t58_tmp) - t91_tmp * t91_tmp);
  t114_tmp = 1.0F / t112;
  t118_tmp = (t36_tmp - t35_tmp) + t112;
  t130 = atanf(t49_tmp * t118_tmp) * 2.0F;
  t133_tmp = cosf(t130);
  t130 = sinf(t130);
  t141_tmp = 1.0F / (t50_tmp * (t118_tmp * t118_tmp) + 1.0F);
  t112 = ((t35_tmp + t61_tmp) - t185) * t50_tmp * t118_tmp +
         t49_tmp * (t33_tmp - t114_tmp *
                                  ((t4_tmp * t58_tmp * 0.05808F -
                                    t6_tmp * t57_tmp * 0.05808F) +
                                   t91_tmp * (t185 - t61_tmp) * 2.0F) /
                                  2.0F);
  t6_tmp = ((t36_tmp + t62_tmp) - t60_tmp) * t50_tmp * t118_tmp +
           t49_tmp * (t34_tmp - t114_tmp *
                                    ((t5_tmp * t58_tmp * 0.05808F -
                                      t7_tmp * t57_tmp * 0.05808F) +
                                     t91_tmp * (t60_tmp - t62_tmp) * 2.0F) /
                                    2.0F);
  t33_tmp = t16_tmp + t133_tmp * 0.132F;
  t35_tmp = t18_tmp + t130 * 0.132F;
  t114_tmp = t33_tmp * t33_tmp;
  t185 = 1.0F / t33_tmp;
  t118_tmp = t35_tmp * t35_tmp + t114_tmp;
  t4_tmp = t133_tmp * t141_tmp;
  t91_tmp = t16_tmp - t4_tmp * t112 * 0.264F;
  t130 *= t141_tmp;
  t50_tmp = t18_tmp - t130 * t112 * 0.264F;
  t112 = F * (1.0F / sqrtf(t118_tmp));
  t49_tmp = Tp * t114_tmp * (1.0F / t118_tmp);
  t118_tmp = t35_tmp * (1.0F / t114_tmp);
  T[0] = t112 * (t35_tmp * t91_tmp * 2.0F - t33_tmp * t50_tmp * 2.0F) / 2.0F +
         t49_tmp * (t185 * t91_tmp + t118_tmp * t50_tmp);
  T[1] = t112 *
             (t4_tmp * t35_tmp * t6_tmp * 0.528F -
              t130 * t33_tmp * t6_tmp * 0.528F) /
             2.0F -
         t49_tmp * (t185 * (0.0F - t4_tmp * t6_tmp * 0.264F) -
                    t118_tmp * (t130 * t6_tmp * 0.264F));
}

/* End of code generation (leg_conv.c) */
