/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * lqr_k.c
 *
 * Code generation for function 'lqr_k'
 *
 */

/* Include files */
#include "lqr_k.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static float rt_powf_snf(float u0, float u1);

/* Function Definitions */
static float rt_powf_snf(float u0, float u1)
{
  float y;
  if (rtIsNaNF(u0) || rtIsNaNF(u1)) {
    y = rtNaNF;
  } else {
    float f;
    y = fabsf(u0);
    f = fabsf(u1);
    if (rtIsInfF(u1)) {
      if (y == 1.0F) {
        y = 1.0F;
      } else if (y > 1.0F) {
        if (u1 > 0.0F) {
          y = rtInfF;
        } else {
          y = 0.0F;
        }
      } else if (u1 > 0.0F) {
        y = 0.0F;
      } else {
        y = rtInfF;
      }
    } else if (f == 0.0F) {
      y = 1.0F;
    } else if (f == 1.0F) {
      if (u1 > 0.0F) {
        y = u0;
      } else {
        y = 1.0F / u0;
      }
    } else if (u1 == 2.0F) {
      y = u0 * u0;
    } else if ((u1 == 0.5F) && (u0 >= 0.0F)) {
      y = sqrtf(u0);
    } else if ((u0 < 0.0F) && (u1 > floorf(u1))) {
      y = rtNaNF;
    } else {
      y = powf(u0, u1);
    }
  }
  return y;
}

void lqr_k(float L0, float K[12])
{
  float t2;
  float t3;
  /* LQR_K */
  /*     K = LQR_K(L0) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     09-May-2026 19:13:20 */
  t2 = L0 * L0;
  t3 = rt_powf_snf(L0, 3.0F);
  K[0] = ((L0 * -42.9759903F - t2 * 834.713379F) + t3 * 3228.25952F) +
         0.317834556F;
  K[1] =
      ((L0 * 30.5160351F - t2 * 24.1315918F) - t3 * 412.332275F) - 0.606049836F;
  K[2] =
      ((L0 * -5.97862148F - t2 * 160.626801F) + t3 * 569.72406F) + 0.100342169F;
  K[3] =
      ((L0 * 6.42428493F - t2 * 12.402257F) - t3 * 49.1732292F) - 0.102529436F;
  K[4] = ((L0 * -28.4629879F - t2 * 280.185211F) + t3 * 1367.10657F) +
         0.547008395F;
  K[5] =
      ((L0 * 20.9805832F - t2 * 88.8476868F) + t3 * 29.4460297F) - 0.245160371F;
  K[6] = ((L0 * -31.0228348F - t2 * 204.988907F) + t3 * 1091.43787F) +
         0.427929342F;
  K[7] =
      ((L0 * 20.9717579F - t2 * 102.052139F) + t3 * 95.2390289F) - 0.259944558F;
  K[8] =
      ((L0 * -108.561981F + t2 * 265.138153F) - t3 * 221.810303F) + 17.995327F;
  K[9] =
      ((L0 * 71.288269F - t2 * 363.537292F) + t3 * 730.836121F) + 18.7268333F;
  K[10] = ((L0 * -4.83956623F + t2 * 17.8434963F) - t3 * 37.9140739F) +
          0.870167911F;
  K[11] =
      ((L0 * 1.76295102F - t2 * 7.26515818F) + t3 * 13.0611944F) + 0.93143183F;
}

/* End of code generation (lqr_k.c) */
